name: Build and Release Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK
        run: cp build/app/outputs/flutter-apk/app-release.apk comandoel.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: comandoel-release-apk
          path: comandoel.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Komandoel v1.0.${{ github.run_number }}
          body: |
            ## 🎮 کوماندوئل

            نسخه جدید بازی کوماندوئل.

            ### دانلود
            فایل APK را از بخش Assets دانلود کنید.
          files: comandoel.apk
          generate_release_notes: true